# Generated by Django 6.0.6 on 2026-09-01 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="stories/%Y/%m/%d/", verbose_name="รูปภาพสตอรี่"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ข้อความสตอรี่"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shared_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_in_stories",
                        to="posts.post",
                        verbose_name="โพสต์ที่แชร์มา",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="เจ้าของสตอรี่",
                    ),
                ),
            ],
            options={
                "verbose_name": "สตอรี่",
                "verbose_name_plural": "สตอรี่ทั้งหมด",
                "ordering": ["-created_at"],
            },
        ),
    ]
