# Generated by Django 6.0.6 on 2026-09-01 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_story"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={
                "ordering": ["created_at"],
                "verbose_name": "สตอรี่",
                "verbose_name_plural": "สตอรี่ทั้งหมด",
            },
        ),
        migrations.RemoveField(
            model_name="story",
            name="image",
        ),
        migrations.AddField(
            model_name="story",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_stories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้กดใจสตอรี่",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="media_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="stories/%Y/%m/%d/",
                verbose_name="ไฟล์รูปภาพหรือวิดีโอสตอรี่",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="media_type",
            field=models.CharField(
                choices=[("image", "รูปภาพ"), ("video", "วิดีโอ")],
                default="image",
                max_length=10,
                verbose_name="ประเภทสื่อ",
            ),
        ),
        migrations.CreateModel(
            name="StoryReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=500, verbose_name="ข้อความ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="posts.story",
                        verbose_name="สตอรี่",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_replies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ตอบกลับ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อความตอบกลับสตอรี่",
                "verbose_name_plural": "ข้อความตอบกลับสตอรี่ทั้งหมด",
                "ordering": ["created_at"],
            },
        ),
    ]
