# Generated by Django 6.0.6 on 2026-09-03 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0003_alter_story_options_remove_story_image_story_likes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("like_post", "ถูกใจโพสต์ของคุณ"),
                            ("comment_post", "แสดงความคิดเห็นบนโพสต์ของคุณ"),
                            ("like_story", "ถูกใจสตอรี่ของคุณ"),
                            ("reply_story", "ตอบกลับสตอรี่ของคุณ"),
                            ("share_story", "แชร์โพสต์ของคุณลงในสตอรี่"),
                            ("follow", "เริ่มติดตามคุณ"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="ประเภทการแจ้งเตือน",
                    ),
                ),
                (
                    "text_preview",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ข้อความตัวอย่าง"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="อ่านแล้วหรือยัง"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="เวลาที่สร้าง"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="posts.comment",
                        verbose_name="ความคิดเห็นที่เกี่ยวข้อง",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="posts.post",
                        verbose_name="โพสต์ที่เกี่ยวข้อง",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้รับแจ้งเตือน",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้กระทำการ",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="posts.story",
                        verbose_name="สตอรี่ที่เกี่ยวข้อง",
                    ),
                ),
            ],
            options={
                "verbose_name": "การแจ้งเตือน",
                "verbose_name_plural": "การแจ้งเตือนทั้งหมด",
                "ordering": ["-created_at"],
            },
        ),
    ]
