# Generated by Django 6.0.6 on 2026-09-03 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="อัปเดตล่าสุด"),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ร่วมสนทนา",
                    ),
                ),
            ],
            options={
                "verbose_name": "การสนทนา",
                "verbose_name_plural": "การสนทนาทั้งหมด",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="ข้อความ")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="chat_images/%Y/%m/%d/",
                        verbose_name="รูปภาพแนบ",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="อ่านแล้ว")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="เวลาส่ง"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                        verbose_name="ห้องสนทนา",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ส่ง",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อความ",
                "verbose_name_plural": "ข้อความทั้งหมด",
                "ordering": ["created_at"],
            },
        ),
    ]
